checkpoint_path: artefacts/etsformer/ordinal_regression_3d.pt
device: !!python/object/apply:torch.device
- cuda
- 0
lr: 0.00169
lr_scheduler: cosine
num_epochs: 100
num_steps_forecast: 24
optimizer: adam
patience: 19
tb_logs: false
verbose: true
